---
# file: roles/hub_code/tasks/main.yml

- name: Create code directories
  file:
    path: "{{item}}"
    state: directory
    owner: "{{ hub_user }}"
    group: "{{ hub_group }}"
    mode: 0750
  with_items:
    - /usr/local/sobun
    - /usr/local/sobun/config
    - /usr/local/sobun/helpers
    - /usr/local/sobun/dist

- name: Copy packaged code over
  copy: src="../../../../sobun/dist/{{ dream_package_name }}" dest=/usr/local/sobun/dist/

- name: Grab prerequisites from source and copy over (@TODO this needs refactored)
  copy: src="../../../../sobun/requirements.txt" dest="/usr/local/sobun/dist/requirements.txt"


- name: Set recursive ownership of synced files
  file:
    path: /usr/local/sobun
    owner: "{{ hub_user }}"
    group: "{{ hub_group }}"
    recurse: True

- name: Install sobun specific prerequisites (pip would do this, but weird errors)
  pip:
    executable: pip3
    requirements: /usr/local/sobun/dist/requirements.txt

- name: Install package
  pip:
    name: "/usr/local/sobun/dist/{{ dream_package_name }}"


- name: Ensure there is an empty measurements.db
  file: name=/usr/local/sobun/measurements.db state=touch owner={{ hub_user }} group={{ hub_group }} mode=0660

- name: Have dream.batcher initialize the db
  command: /usr/bin/python3 -m dream.batcher --reset
  args:
    chdir: /usr/local/sobun
